#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use App\Command\CalculateMetricCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new CalculateMetricCommand());
$application->add(new \App\Command\StyleTestCommand());

try {
    $application->run();
} catch (Exception $e) {
    print 'failed with message: ' . $e->getMessage();
    print PHP_EOL;
}
